name: Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Yarn Canary version
        run: yarn set version canary

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          clean: true
          clean-exclude: |
            .nojekyll